export const STYLE_OPTIONS: Record<string, Record<string, string>> = {
  style_pace: {
    slow: 'a slow and deliberate pace',
    gentle: 'a gentle, unhurried pace',
    'medium-slow': 'a calm, measured tempo',
    'slow-breath': 'a breath-paced rhythm',
    medium: 'a steady, natural rhythm',
    'micro-paused': 'with micro-pauses inviting silence',
    'flow-paused': 'alternating flow and reflective stillness',
    hovering: 'with a hovering, lingering rhythm',
  },
  style_tone: {
    'neutral-deep': 'a calm and contemplative tone',
    'warm-personal': 'a warm, personal tone',
    'symbolic-reflective': 'a symbolic and thoughtful tone',
    'playful-visual': 'a playful, image-rich tone',
    'calm-archival': 'a calm and precise tone',
    'evocative-gentle': 'a gently evocative tone',
    enigmatic: 'a mysterious, layered tone',
    inviting: 'an inviting, open tone',
    'clear-objective': 'a clear and grounded tone',
    'tender-honest': 'a tender, yet honest tone',
    'contemplative-vast': 'a vast and contemplative tone',
    'humble-curious': 'a humble, curious tone, open to discovery',
    'quiet-revealing': 'a quiet tone that subtly reveals depth',
  },
  style_rhythm: {
    ritualistic: 'with a ritual-like rhythm',
    fluid: 'in a flowing, natural rhythm',
    cyclical: 'returning in cycles, like seasons',
    'wave-like': 'like the movement of waves',
    'spiral-linear': 'unfolding in a spiral, yet directed line',
    layered: 'with gently layered rhythm',
    labyrinthine: 'exploring winding inner paths',
    grounded: 'a steady and anchored rhythm',
    linear: 'a step-by-step, linear unfolding',
    'breath-linked': 'linked to the natural rhythm of breath',
    'echoing-layered': 'with echoing, gradually layered rhythm',
    'still-flow': 'stillness flowing into motion, and back',
  },
  style_structure: {
    spiral: 'unfolding like a spiral',
    relational: 'guided by relationship and resonance',
    narrative: 'following a storytelling arc',
    associative: 'moving through associations',
    'summary-reflective': 'summarizing with reflective pauses',
    drifting: 'gently drifting between thoughts',
    'mythic-paradoxical': 'with poetic, sometimes paradoxical flow',
    sequential: 'a clear, step-by-step logic',
    structured: 'a clearly organized structure',
    fractal: 'with a self-similar, fractal unfolding',
    'echo-looped': 'echoing earlier thoughts in loops',
    'anchored-expansive': 'anchored in clarity, expanding gently outward',
  },
  style_visuality: {
    high: 'strongly image-rich',
    low: 'low in imagery',
    temporal: 'evoking inner shifts over time',
    patterned: 'using recognizable visual motifs',
    dreamlike: 'dreamlike visual impressions',
    sensory: 'grounded in sensory images',
    minimal: 'minimal or abstract imagery',
    'internal-gesture': 'evoking inner gestures or postures',
    'subtle-symbolic': 'subtly woven symbolic imagery',
    elemental: 'working with elemental images (earth, water, air, fire)',
  },
  style_directiveness: {
    passive: 'passive, allowing space',
    reflective: 'gently mirroring the user',
    guiding: 'softly guiding the direction',
    echoing: "echoing and rephrasing the user's tone",
    questioning: 'gently inquisitive',
    'gentle-guiding': 'lightly leading without pressure',
    'non-directive': 'supportive, without steering',
    'evocative-inviting': 'evoking direction through invitation',
    'spiral-guiding': 'gently spiraling towards insight',
    'intuitive-prompting': 'intuitively prompting next inner steps',
  },
  style_emphasis: {
    subtle: 'subtle transitions',
    balanced: 'balanced emphasis',
    strong: 'strong emphasis',
  },
  style_breaks: {
    'after key points': 'pauses after key points',
    frequent: 'frequent short breaks',
    minimal: 'minimal explicit breaks',
  },
};